#!/bin/python3

import math
import os
import random
import re
import sys


def sockMerchant(n, arr):
    count = []
    traversed = []

    for i in range(0,len(arr)):
        if arr[i] not in traversed:
            count.append(arr.count(arr[i]))
            traversed.append(arr[i])
    sum = 0
    for i in range(0,len(count)):
        sum = sum + count[i]//2
        
    return sum

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
